services:
  postgres:
    image: postgres:16
    container_name: fastify_postgres_dev
    restart: always
    environment:
      POSTGRES_USER: fastify_user
      POSTGRES_PASSWORD: fastify_pass
      POSTGRES_DB: fastify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fastify_app_dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://fastify_user:fastify_pass@postgres:5432/fastify_db
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    command: pnpm run dev

volumes:
  postgres_data_dev:
